INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (26498, 'Never Gonna Give You Up', 'Rick Astley', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (27793, 'Peaches', 'Jack Black', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (2896, 'Hotel California', 'Eagles', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (8216, 'Titantic', 'movie themes', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (7037, 'Youre Beautiful', 'James Blunt', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (8206, 'My Humps', 'Black Eyed Peas', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11544, 'Poker Face', 'Lady GaGa', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (12652, 'Hes a Pirate', 'Pirates of the Caribbean', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (2079, 'Pink Panther', 'movie themes', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (1564, 'Harry Potter', 'Harry Potter', 240);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (2240, 'James Bond', 'movie themes', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (4546, 'Numb', 'Linkin Park', 960);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11438, 'Viva la Vida (2)', 'Coldplay', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11459, 'Hallelujah', 'Leonard Cohen', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (8046, 'Axel F', 'Crazy Frog', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (8373, 'Super Mario Brothers', 'video games', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (849, 'Family Guy', 'tv themes', 240);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (1526, 'Godfather', 'movie themes', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11353, 'You Raise Me Up', 'Josh Gorban', 384);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (8871, 'Mission Impossible', 'movie themes', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11624, 'Happy Birthday', 'Birthday', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (13184, 'Gangnam Style', 'PSY', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (3093, 'Wonderful Tonight', 'Eric Clapton', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (5169, 'Billie Jean', 'Michael Jackson', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (1827, 'Simpsons', 'tv themes', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (9111, 'Dancing Queen', 'ABBA', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (4596, 'Sweet Home Alabama', 'Lynyrd Skynyrd', 384);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (5772, 'Bohemian Rhapsody', 'Queen', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (5168, 'Beat It', 'Michael Jackson', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (5879, 'Because Of You', 'Kelly Clarkson', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (1284, 'Piano Man', 'Billy Joel', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (3634, 'Sweet Child Of Mine', 'Guns N Roses', 960);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (2983, 'Lose Yourself', 'Eminem', 384);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (3137, 'Bring Me To Life', 'Evanescence', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (12253, 'Baby', 'Justin Bieber', 960);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (12550, 'Someone Like You', 'Adele', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (12548, 'Rolling in the deep', 'Adele', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (7857, 'Another Brick In The Wall', 'Pink Floyd', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (5860, 'We Will Rock You', 'Queen', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (12275, 'Grenade', 'Bruno Mars', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (4074, 'A Thousand Miles', 'Vanessa Carlton', 384);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (7481, 'Candy Shop', '50 Cent', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (1928, 'Its My Life', 'Bon Jovi', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (197, 'Back In Black', 'AC DC', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (2477, 'Clocks', 'Coldplay', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (7399, 'United States', 'national anthems', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (7036, 'Dont Cha', 'Pussycat Dolls', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (3140, 'My Immortal', 'Evanescence', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11196, 'Final Countdown', 'Europe', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (1829, 'Spong Bob Squar Pants Theme', 'tv themes', 960);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (6017, 'Wake Me Up When September Ends', 'Green Day', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (16807, 'In The End', 'Linkin Park', 240);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (2756, 'Smoke On The Water', 'Deep Purple', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (2033, 'Matrix', 'movie themes', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (2099, 'Rocky', 'movie themes', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (844, 'Fresh Prince Of Bel Air', 'tv themes', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (12475, 'Just The Way You Are', 'Bruno Mars', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (5187, 'Thriller', 'Michael Jackson', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11776, 'I Got A Feeling', 'Black Eyed Peas', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11747, 'Bad Romance', 'Lady GaGa', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11543, 'Just Dance', 'Lady GaGa', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (1525, 'Gladiator', 'movie themes', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11541, 'Im Yours', 'Jason Mraz', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (7110, 'If I Aint Got You', 'Alicia Keys', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (174, 'In Da Club', '50 Cent', 384);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11194, 'Everytime We Touch', 'Cascada', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (7105, 'Fix You', 'Coldplay', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (7795, 'Lord Of The Rings', 'Lord Of The Rings', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (10608, 'Unfaithful', 'Rihanna', 256);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (2147, 'Superman', 'movie themes', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (4563, 'We Are The World', 'Lionel Richie', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (150, 'Here Without You', '3 Doors Down', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (1377, 'Back To The Future - Main Them', 'movie themes', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (5099, 'Enter Sandman', 'Metallica', 384);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (3532, 'Boulevard of Broken Dreams', 'Green Day', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (12665, 'The lazy song', 'Bruno Mars', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (5100, 'Nothing Else Matters', 'Metallica', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (6049, 'Californication', 'Red Hot Chili Peppers', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11394, 'Beautiful Girls', 'Sean Kingston', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11406, 'Umbrella', 'Rihanna', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (7661, 'Feel Good Inc', 'Gorillaz', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (3953, 'Seven Nation Army', 'White Stripes', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11384, 'Smack that', 'Akon', 960);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (12549, 'Set Fire to the Rain', 'Adele', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (12738, 'Someone like you wit lyric', 'Adele', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (4828, 'Ring Of Fire', 'Johnny Cash', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (6772, 'B.Y.O.B.', 'System of a Down', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11431, 'I Kissed A Girl', 'Katy Perry', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (8109, 'American Idiot', 'Green Day', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (4149, 'Lonely', 'Akon', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (8297, 'Hips Dont Lie', 'Shakira', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (2331, 'All I Want For Christmas Is Yo', 'Christmas', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (1343, 'Addams Family', 'movie themes', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (8800, 'Theme', 'Super Mario Brothers', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (7704, 'Cliffs Of Dover', 'Eric Johnson', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (2933, 'Can You Feel The Love Tonight', 'Elton John', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (8129, 'Lets Get It Started', 'Black Eyed Peas', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (1891, 'UEFA - Champions League', 'tv themes', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (7796, 'Concerning Hobbits', 'Lord Of The Rings', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (2804, 'Sultans Of Swing', 'Dire Straits', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (1973, 'Indiana Jones', 'movie themes', 48);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (2329, '12 Days Of Christmas', 'Christmas', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (761, 'Hail To The Chief', '4th of July', 384);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (9135, 'Chiquitita', 'ABBA', 384);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11356, 'Girlfriend', 'Avril Lavigne', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (2288, 'Everything I Do', 'Bryan Adams', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (1652, 'No Woman No Cry', 'Bob Marley', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (6379, 'Black Magic Woman', 'Santana', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (5176, 'Heal The World', 'Michael Jackson', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (1317, 'Where Is The Love', 'Black Eyed Peas', 960);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (751, 'C.S.I : Criminal Scene Investi', 'tv themes', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11960, 'Fireflies', 'Owl City', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11469, 'Hot N Cold', 'Katy Perry', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (12257, 'You Belong With Me', 'Taylor Swift', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (13138, 'The Hobbit - Misty Mountain Co', 'movie themes', 960);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (5260, 'Time Is Running Out', 'Muse', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (9406, 'My Way', 'Frank Sinatra', 240);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (12266, 'Firework', 'Katy Perry', 96);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (4146, 'Dont Phunk With My Heart', 'Black Eyed Peas', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (588, 'Complicated', 'Avril Lavigne', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (3620, 'Knocking On Heavens Door', 'Guns N Roses', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (4094, 'YMCA', 'Village People', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (3116, 'Tears In Heaven', 'Eric Clapton', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (1047, 'Hey Jude', 'Beatles', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (4834, 'I Walk The Line', 'Johnny Cash', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11750, 'Love Story', 'Taylor Swift', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (12480, 'Marry You', 'Bruno Mars', 1024);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (827, '2001 A Space Oddysey', 'movie themes', 384);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (10887, 'Home', 'Michael Buble', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (12726, 'Just The Way you Are.with Lyri', 'Bruno Mars', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (12167, 'A Thousand Years', 'Toto', 384);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (836, 'Friends', 'tv themes', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (8112, 'Bamboleo', 'Gypsy Kings', 384);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (4159, 'This Love', 'Maroon 5', 240);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (9711, 'Still Got The Blues', 'Gary Moore', 384);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (4816, 'Imagine', 'John Lennon', 192);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11383, 'Dont Matter', 'Akon', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (8842, 'Theme B', 'Tetris', 120);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (3621, 'November Rain', 'Guns N Roses', 384);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (175, 'P.I.M.P.', '50 Cent', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (11503, 'If I Were A Boy', 'Beyonce', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (5173, 'Earth Song', 'Michael Jackson', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (9080, 'Chasing Cars', 'Snow Patrol', 480);
INSERT INTO songs (midi_id, title, dir, ticks_per_beat) VALUES (1202, 'Yesterday', 'Beatles', 480);